Unloaded dependency: anaconda3/2020.11

CommandNotFoundError: Your shell has not been properly configured to use 'conda deactivate'.
To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.



CommandNotFoundError: Your shell has not been properly configured to use 'conda deactivate'.
To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.


Unloading the anaconda2 module (if loaded)...
Loaded dependency: anaconda3/2020.11
AI/Version: anaconda3.2020.11
-----------------------------

Description
-----------
The modulefile AI/anaconda3.2020.11 provides a unified, rich, anaconda3 based
environment for Artificial Intelligence(AI)/Machine Learning(ML)/Big Data(BD)
on top of based on Python 3.

Module contents
---------------
Several popular AI/ML/BD packages are included in this environment, such as:
    tensorflow-gpu, theano, keras-gpu, pytorch, opencv, pandas, scikit-learn,
scikit-image etc.

To check the full list of available packages in this environment, first
activate it and then run the command
    conda list

Main packages included in this module:
* astropy 4.2
* blas 1.0
* bokeh 2.2.3
* cudatoolkit 10.0.130
* cudnn 7.6.5
* h5py 2.8.0
* hdf5 1.10.2
* ipython 7.19.0
* jupyter 1.0.0
* jupyterlab 2.2.6
* keras-gpu 2.3.1
* matplotlib 3.3.2
* mkl 2019.4
* nccl 1.3.5
* networkx 2.5
* ninja 1.10.2
* nltk 3.5
* notebook 6.1.6
* numba 0.51.2
* numpy 1.17.0
* opencv 3.4.2
* pandas 1.2.0
* pillow 8.1.0
* pip 20.3.3
* python 3.8.5
* pytorch 1.5.0
* scikit-learn 0.23.2
* scipy 1.5.2
* seaborn 0.11.1
* tensorboard 1.15.0
* tensorflow-gpu 1.15.0
* theano 1.0.4

If you need to further customize this environment (e.g., install additional
packages, or upgrade a particular package),
you should first clone this environment as follows:
    conda create --prefix <path to a dir in which you can write> --clone
$AI_ENV
Then activate the newly spawned environment and proceed with your
customization.

To get further help with conda usage, you can try one of the following:
    conda -h
    conda <command> -h

Activate the module
-------------------
Before activating, make sure you are on a GPU node of Bridges2 if you wish to
use the components built to run on GPUs.
To activate the environment, run the following commands:
    # module load AI/anaconda3.2020.11
    source activate $AI_ENV
        # OR
    conda activate $AI_ENV # This might require you to run "conda init" first.

Dealing with 20210812_JamesElizabethBrianWithShark_shark_0.json
Traceback (most recent call last):
  File "tracking/run_tracker.py", line 322, in <module>
    img_list, init_bbox, gt, savefig_dir, display, result_path = gen_config(args)
  File "/ocean/projects/cis220010p/wzhangk/cv_project/py-MDNet/tracking/gen_config.py", line 35, in gen_config
    param = json.load(open(args.json, 'r'))
FileNotFoundError: [Errno 2] No such file or directory: '20210812_JamesElizabethBrianWithShark_shark_0.json'
Dealing with 20210812_JamesElizabethBrianWithShark_human_2.json
Traceback (most recent call last):
  File "tracking/run_tracker.py", line 322, in <module>
    img_list, init_bbox, gt, savefig_dir, display, result_path = gen_config(args)
  File "/ocean/projects/cis220010p/wzhangk/cv_project/py-MDNet/tracking/gen_config.py", line 35, in gen_config
    param = json.load(open(args.json, 'r'))
FileNotFoundError: [Errno 2] No such file or directory: '20210812_JamesElizabethBrianWithShark_human_2.json'
Dealing with 20210812_JamesElizabethBrianWithShark_human_1.json
Traceback (most recent call last):
  File "tracking/run_tracker.py", line 322, in <module>
    img_list, init_bbox, gt, savefig_dir, display, result_path = gen_config(args)
  File "/ocean/projects/cis220010p/wzhangk/cv_project/py-MDNet/tracking/gen_config.py", line 35, in gen_config
    param = json.load(open(args.json, 'r'))
FileNotFoundError: [Errno 2] No such file or directory: '20210812_JamesElizabethBrianWithShark_human_1.json'
Dealing with 20210812_JamesElizabethBrianWithShark_shark_2.json
Traceback (most recent call last):
  File "tracking/run_tracker.py", line 322, in <module>
    img_list, init_bbox, gt, savefig_dir, display, result_path = gen_config(args)
  File "/ocean/projects/cis220010p/wzhangk/cv_project/py-MDNet/tracking/gen_config.py", line 35, in gen_config
    param = json.load(open(args.json, 'r'))
FileNotFoundError: [Errno 2] No such file or directory: '20210812_JamesElizabethBrianWithShark_shark_2.json'
